[project]
name = "quickstart"
version = "0.1.0"
description = "A repo for getting started with Prefect."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "prefect",
    "prefect-cloud",
]
